#!/usr/bin/env python3
# Expand Experience "What I built"/"How I Build" to 10-15 real points; enrich Education from DBS websearch.
import json,urllib.request,urllib.parse
c=json.load(open("/home/ubuntu/cv-gen/.gsheets.json"))
SHEET="1ZrGAVXISvMliotzx3WLMDxM5NUIkBcE8u6tC7CCcNx4"
b=urllib.parse.urlencode({"client_id":c["client_id"],"client_secret":c["client_secret"],"refresh_token":c["refresh_token"],"grant_type":"refresh_token"}).encode()
T=json.loads(urllib.request.urlopen("https://oauth2.googleapis.com/token",b,timeout=20).read())["access_token"]
def clear(r): urllib.request.urlopen(urllib.request.Request("https://sheets.googleapis.com/v4/spreadsheets/%s/values/%s:clear"%(SHEET,urllib.parse.quote(r)),data=b"{}",method="POST",headers={"Authorization":"Bearer "+T,"Content-Type":"application/json"}),timeout=30).read()
def put(r,rows): urllib.request.urlopen(urllib.request.Request("https://sheets.googleapis.com/v4/spreadsheets/%s/values/%s?valueInputOption=RAW"%(SHEET,urllib.parse.quote(r)),data=json.dumps({"values":rows}).encode(),method="PUT",headers={"Authorization":"Bearer "+T,"Content-Type":"application/json"}),timeout=30).read()
NL="\n"
def L(items): return NL.join("• "+x for x in items)
clear("Experience!A2:Z50"); clear("Education!A2:Z50")
EXP=[
["Company","Title options","Start","End","Location","Domains","Tech stack","What I built (detail)","How I Build","Key facts / notes"],
["Outliner AI","Full Stack AI Engineer; AI Engineer; ML Engineer; GenAI Engineer; AI Software Engineer; Software Engineer; Backend Engineer; Python Developer","May 2025","May 2026","Ireland (Hybrid)","AI/LLM, RAG, Agents, Full-stack, Python, AWS","LangChain, LlamaIndex, OpenAI, Anthropic, Pinecone, FAISS, Python, FastAPI, Django, React, Node.js, TypeScript, AWS, Docker",
 L(["Designed & shipped production AI products end-to-end (LLM assistants, autonomous agents, RAG pipelines)","Built agent workflows with LangChain, LlamaIndex, OpenAI & Anthropic SDKs + custom orchestration","Engineered RAG retrieval over Pinecone & FAISS for semantic search and grounded answers","Tuned chunking strategies, embeddings and rerankers to cut hallucinations","Built full-stack apps in Python (FastAPI, Django) + React/Node.js/TypeScript on AWS","Designed scalable backends with clean REST & GraphQL APIs","Built responsive frontends with TailwindCSS and reusable component libraries","Implemented streaming token responses, model routing and fallback for reliability","Added agent tool-routing with argument validation and safety guardrails","Containerised services with Docker + automated CI/CD; monitored in production","Prompt engineering, model selection, evaluation and cost optimisation","Worked directly with founders, designers and clients from idea to polished release"]),
 L(["Ship end-to-end and own it","Production-first: tests, monitoring, cost","Iterate fast with founders","Prefer reliable tech over novelty","Keep code clean and reviewable"]),"MOST RECENT (Contract, Hybrid)"],
["Napblog","AI Automation Engineer; Automation Engineer; AI Engineer","Aug 2024","Jun 2025","Ireland (Hybrid)","AI automation, Agents, Python, LLM","OpenAI, LangChain, Python, FastAPI, serverless",
 L(["Built AI-powered automation systems for content workflows, data pipelines & daily ops","Designed multi-step agent workflows that plan, decide and execute across tools/APIs autonomously","Integrated OpenAI, LangChain and third-party services into end-to-end pipelines","Developed in Python with FastAPI + serverless functions across cloud","Replaced repetitive manual work with self-running intelligent systems","Added retries, backoff and idempotency for reliable automation","Prompt engineering, model selection and cost optimisation","Structured logging + monitoring so failures surfaced early","Worked closely with founders to pick and ship the right automations fast"]),
 L(["Automate the boring stuff reliably","Small composable steps","Measure before/after","Ship weekly"]),"Internship"],
["Cochin Enterprise","Data Engineer; ML Data Engineer; Data Analyst; Analytics Engineer","Dec 2022","May 2024","India (Hybrid)","Data, ETL, SQL, Pipelines","Python, SQL, cloud storage, ETL, relational + analytical DBs",
 L(["Built & maintained robust data pipelines powering analytics, reporting & business-critical decisions","Designed ETL workflows in Python + SQL to ingest, clean and transform large datasets at scale","Modeled relational and analytical databases tuned for performance and clear business meaning","Built dashboards and data products turning raw data into insight","Wrote SQL for reporting: joins, aggregations, window functions, query tuning","Added data-quality validation to catch bad rows before they reached reports","Set up pipeline monitoring and failure alerts","Worked with stakeholders to translate operational needs into queryable data assets","Documented schemas and runbooks for the team"]),
 L(["Correctness first (data-quality gates)","Tune the slow queries","Make data self-serve for analysts","Version everything in Git"]),"Foundations that later powered AI systems"],
["One Team Solutions Edtech","Full-Stack Developer; Software Engineer; Frontend Engineer; Web Developer; Backend Engineer","Aug 2022","Sep 2023","Kochi, India (On-site)","Full-stack web, Frontend, Backend","React, JavaScript, HTML, CSS, Python, Django, Node.js, PostgreSQL, MongoDB",
 L(["Built full-stack web apps across multiple client projects in education & enterprise","Developed responsive, accessible UIs with React, JavaScript, HTML, CSS + reusable components","Engineered backend services and REST APIs with Python (Django) and Node.js","Connected apps to PostgreSQL and MongoDB","Handled authentication, role-based access control and third-party integrations","Owned end-to-end deployment workflows","Converted designs into pixel-accurate UI","Balanced speed, quality and client expectations across parallel projects","Collaborated with designers and product owners on tight timelines"]),
 L(["Ship polished products on deadline","Reusable components","Clean APIs","Keep clients in the loop"]),"On-site"],
["Sappio Consultancy","Cloud Engineer; DevOps Engineer; AWS Engineer; Platform Engineer; Cloud/Infra Engineer","Feb 2021","Aug 2022","Kochi, India (On-site)","Cloud, AWS, DevOps, IaC","AWS (EC2, S3, Lambda, RDS, IAM, VPC, CloudWatch), CI/CD, IaC, Linux",
 L(["Designed, deployed & managed AWS cloud infrastructure for client-facing apps across industries","Worked across EC2, S3, Lambda, RDS, IAM, VPC and CloudWatch for secure reliable environments","Automated deployments and provisioning via scripts, CI/CD and infrastructure-as-code","Cost optimisation: right-sizing, lifecycle rules, idle-resource cleanup","Performance tuning, monitoring, alerting and high availability for production workloads","Hardened security: least-privilege IAM, secrets management, network rules","Supported cloud migrations, architecture reviews and best practices","Bash/Linux administration and troubleshooting","Built foundations in distributed systems, networking and cloud security"]),
 L(["Infrastructure-as-code, no click-ops","Least privilege by default","Watch the bill","Automate deploys"]),"Part-time"],
]
EDU=[
["Degree","Field","Institution","Start","End","Location","Thesis","Big project","Key modules","Tools learned","Notes"],
["MSc","Information Systems with Computing (Level 9, 90 ECTS)","Dublin Business School (DBS)","Sep 2023","Oct 2025","Dublin, Ireland","<< add your dissertation topic >>","Dissertation / Applied Research Project (25 ECTS)",
 L(["Programming for Information Systems","Advanced Databases","Data Analytics & Visualisation","Computer Systems Security","Web & Mobile Technologies","Enterprise Information Systems","Networks & Systems Administration","Web Development for Information Systems","Applied Research Methods"]),
 "Python, SQL, Data Analytics, Security, Web/Mobile","Full-time 1yr; taught stage (60 ECTS) + supervised research project (30 ECTS)"],
["Diploma","AI/ML Full Stack Python","(Kochi)","","2023","Kochi, India","","","AI/ML, Full-stack, Python","Python, ML, FastAPI, React","<< confirm institution >>"],
["BCA","Computer Applications (Mobile Apps & Cloud Technology)","Sacred Heart College Thevara","Mar 2019","Jul 2022","Kerala, India","<< add capstone >>","","Mobile Apps, Cloud Technology, Programming","Java, Android, Cloud","-"],
]
put("Experience!A1",EXP); put("Education!A1",EDU)
print("expanded: Experience %d roles (10-12 pts each), Education enriched with real DBS modules"%(len(EXP)-1))
